  name: Build EXE                                                                                                                                               
  on:                                                                                                                                                           
    push:                                                         
    workflow_dispatch:
  jobs:                                                                                                                                                         
    build:
      runs-on: windows-latest                                                                                                                                   
      steps:                                                      
        - uses: actions/checkout@v4
        - uses: actions/setup-dotnet@v4                                                                                                                         
          with:
            dotnet-version: '8.0.x'                                                                                                                             
        - name: Publish exe                                       
          shell: pwsh                                                                                                                                           
          run: dotnet publish RotateScreen/RotateScreen.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true
  -p:IncludeNativeLibrariesForSelfExtract=true -o out                                                                                                           
        - uses: actions/upload-artifact@v4                        
          with:                                                                                                                                                 
            name: RotateScreen-exe                                
            path: out/RotateScreen.exe
            retention-days: 30
